version: "2.8"

services:
  # app:
  #   # image: service:local #if build before
  #   build:
  #     dockerfile: Dockerfile
  #   container_name: app
  #   # ports:
  #   #   - "8080:8080"
  #   depends_on:
  #     - postgresql
  #   # networks:
  #   #   - app

  # postgresql:
  #   image: postgres:14-alpine
  #   container_name: psql
  #   environment:
  #     - POSTGRES_DB=${POSTGRES_DB}
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD${POSTGRES_PASSWORD}
  #   volumes:
  #     - ./data:/var/lib/postgresql/data
    # networks:
    #   - app

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

# networks:
#   app: